name: Unit Tests with Postgres
on: [push, pull_request]

jobs:
  run-unit-tests-postgres:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Unit Tests with Postgres
        run: make test-postgres
